apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    env: prod
    tier: production
    platform/owner: platform-team
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: prod-quota
  namespace: prod
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    persistentvolumeclaims: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: prod-limits
  namespace: prod
spec:
  limits:
  - default:
      cpu: 2
      memory: 2Gi
    defaultRequest:
      cpu: 250m
      memory: 256Mi
    type: Container
