# Platform App - infrastructure components
# - platform-bootstrap: namespaces, quotas (platform/environments)
# - platform-ingress-nginx: ingress controller
# - cert-manager, prometheus: optional (uncomment)
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-bootstrap
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/your-org/gitops-platform-sample.git
    path: platform/environments
    targetRevision: main
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.8"
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            type: NodePort
        # For AKS: patch to LoadBalancer or use values-aks overlay
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
# Optional: cert-manager - uncomment to enable
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: platform-cert-manager
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: platform
#   source:
#     chart: cert-manager
#     repoURL: https://charts.jetstack.io
#     targetRevision: v1.13.0
#     helm:
#       releaseName: cert-manager
#       values: |
#         installCRDs: true
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: cert-manager
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
---
# Optional: Prometheus stack - uncomment to enable
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: platform-prometheus
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: platform
#   source:
#     chart: kube-prometheus-stack
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: "55.0.0"
#     helm:
#       releaseName: prometheus
#       values: |
#         prometheus:
#           prometheusSpec:
#             serviceMonitorSelectorNilUsesHelmValues: false
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
